os: osx
osx_image: xcode11
language: swift
script: xcodebuild clean build test -project MyAwesomeApp/MyAwesomeApp.xcodeproj -scheme "MyAwesomeApp" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.0,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO 