"podfile": "podfile"
"language": "swift"
"osx_image": "xcode11"
"xcode_sdk": "iphonesimulator12.0"
before_script:
- gem install fastlane --no-ri --no-rdoc --no-document
- gem install danger --no-ri --no-rdoc --no-document
- gem install danger-swiftlint --no-ri --no-rdoc --no-document
- if [ $DANGER == "ALLOW" ]; then
danger;
./Pods/SwiftLint/swiftlint lint --config .swiftlint-ci.yml;
fi
matrix:
fast_finish: true
include:
- osx_image: xcode11
env: CI_BUILD_TARGET='nap' CI_DEVICE='iPhone X (12.0)' DANGER="ALLOW"
- osx_image: xcode11
env: CI_BUILD_TARGET='nap' CI_DEVICE='iPad Air 2 (12.0)'
